### PR TITLE
Travis-CI has added support for ARM64.Added ARM64 jobs in Travis-CI.

### PR DESCRIPTION
**Pull request by ossdev07**
Added ARM64 jobs in Travis-CI

### CODE REVIEW

**Comment by rhenwood-arm** [comment]
@ossdev07: I find it very difficult to quickly scan for 'arm64' and 'amd64' lines. Is there a better way to express testing these two platforms in travis-ci yaml?

**Comment by QuLogic** [comment]
Does Travis not do matrix expansion on `arch`? Also, there's no compiled code in cycler, so I'm not sure there's much benefit to testing on two arches.

**Comment by tacaswell** [comment]
I suspect that @rhenwood-arm can provide some insight on if it is worth testing cycler on arm.

Given that it is pure-python I don't think we would be doing anything other than testing python-on-arm.  On the other hand no one ever _thinks_ they are doing something funny that is going to break on a different architecture so testing can't hurt.

**Comment by Kojoley** [comment]
> Does Travis not do matrix expansion on `arch`?

Yes, it does. https://docs.travis-ci.com/user/multi-cpu-architectures/#testing-on-multiple-cpu-architectures

**Comment by rhenwood-arm** [comment]
https://github.com/matplotlib/matplotlib has had regressions on Arm and is a requirement of this project so that project is probably the most valuable place for CI for AArch64 today. @ossdev07 : I suggest at first you look into adding a Travis-CI job for Matplotlib - and use the matrix expansion to enhance readability.

**Comment by tacaswell** [comment]
Did the ARM regressions on Matplotlib get reported to us?  We have a fair amount of c++ code in Matplotlib so I would expect it to have more issues than cycler.

Definitely :+1: on getting an arm job on matplotlib/matplotlib, however we probably only want 1 or two (latest python only?) as our full test suite already takes a long time to run.

**Comment by Kojoley** [comment]
Numpy lacks wheels for arm64 and building it fails with a compiler crash https://travis-ci.org/Kojoley/matplotlib/jobs/633312381

**Pull request closed without merging**
