### PR TITLE
Update Python versions

### PR DESCRIPTION
**Pull request by hugovk**
And add `python_requires` to help pip.

Latest master fails on the old 2.7 on Appveyor: https://ci.appveyor.com/project/hugovk/cycler/build/1.0.1

### CODE REVIEW

**Comment by Kojoley** [comment]
Is `PYTHON_VERSION` and `PYTHON_ARCH` used anywhere?

**Comment by hugovk** [comment]
Yes, they're used by https://github.com/matplotlib/cycler/blob/master/ci/appveyor/install.ps1

**Comment by Kojoley** [comment]
You are right... then a path you defined for 3.6 interfere with appveyor installed python.

**Comment by hugovk** [comment]
Which line interferes?

At least AppVeyor passes: https://ci.appveyor.com/project/hugovk/cycler/build/1.0.4

By the way, should AppVeyor be enabled for this repo? Then you get builds for PRs on AppVeyor and Travis.

**Comment by Kojoley** [comment]
> Which line interferes?

Appveyor has installed python under `C:\Python36-x64` path https://www.appveyor.com/docs/build-environment/#python.
Actually I do not know why we are downloading and installing the python. It looks unnecessary to me.

> By the way, should AppVeyor be enabled for this repo?

@tacaswell could you please enable appveyor on organization account for cycler? It looks like I can't do it myself.

**Comment by hugovk** [comment]
I'm not sure Why Python is downloaded rather then using the existing versions, but I bet there was a good reason. Maybe a specific version was needed. Does @tacaswell know?

Should we try it out with the system Pythons?

**Comment by tacaswell** [comment]
power-cycled to see if appveyor will fire.

Those old build failures look like dependency issues (missing setuptools) rather than cycler not working with old versions of 2.7.

**Comment by tacaswell** [comment]
ohh, sorry, not reading the urls clearly (@hugovk 's account above and the emails I got from appveyor were tied to my personal account not matplotlib's).  I'll see if I can sort this out when not on tethered-to-phone internet.

**Comment by Kojoley** [comment]
> Those old build failures look like dependency issues (missing setuptools) rather than cycler not working with old versions of 2.7.

Yeah, cycler uses `python setup.py install`, so `setuptools` should have been installed before calling it.

**Comment by hugovk** [comment]
Is there anything I can do to move this closer to merge?

**Comment by tacaswell** [comment]
https://ci.appveyor.com/project/matplotlib/cycler appveyor should be active now

**Comment by tacaswell** [comment]
'power cycled' again to trigger appveyor.

No good reason to not use the system python.  This appevyor configuration file was cargo-cult-ed from matplotlib/matplotlib which needs to compile c/c++.  It can probably be greatly simplified.

**Comment by Kojoley** [comment]
@hugovk I have rebased and forcepushed to your branch.

**Comment by tacaswell** [comment]
I am quite happy that this is a -250 line PR

**Comment by tacaswell** [comment]
Thanks @Kojoley and @hugovk !

**Pull request merged**
